name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 9.0.x
            
      - name: Publish Blazor project
        run: dotnet publish -c Release -o release DosageCalculator/DosageCalculator.csproj

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DSG_CALC }}
          channelId: live
          projectId: dsg-calc
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
